### ISSUE TITLE
Project Overview

### ISSUE THREAD

**Issue by hmontero1205** [Charlemagnedeux/dvp-u3-constellations#1]
Overall, your work almost met the project specifications...
Your 2D visualization is fine, but your 3D projection is incorrect. All the points are on z = 0! 
This is because you are not using the return value of `fig_3d.add_subplot(1,1,1,projection='3d')` to call scatter on. So, your code should look something like this:
```
ax = fig_3d.add_subplot(1,1,1,projection='3d')
constellation3d = ax.scatter(x,y,z)
```

Please test out your code and make sure everything is correct before submitting next time! Best of luck! :)

**Comment by Charlemagnedeux** [comment]
Thank you Hans for giving me this useful advice.
